killerPerksObject = [
    {"id":0, "name":"Barbecue & Chilli"},
    {"id":1, "name":"Hex Ruin"},
    {"id":2, "name":"Tinkerer"},
    {"id":3, "name":"Pop Goes The Weasel"},
    {"id":4, "name":"Corrupt Intervention"},
    {"id":5, "name":"Discordance"},
    {"id":6, "name":"Starstruck"},
    {"id":7, "name":"A Nurse's Calling"},
    {"id":8, "name":"Thrilling Tremors"},
    {"id":9, "name":"Save The Best For Last"},
    {"id":10, "name":"Hex Devour Hope"},
    {"id":11, "name":"Infectious Fright"},
    {"id":12, "name":"Hex Undying"},
    {"id":13, "name":"Lethal Pursuer"},
    {"id":14, "name":"Make Your Choice"},
    {"id":15, "name":"Sloppy Butcher"},
    {"id":16, "name":"Surveillance"},
    {"id":17, "name":"Hex No One Escapes Death"},
    {"id":18, "name":"Bamboozle"},
    {"id":19, "name":"Monitor & Abuse"},
    {"id":20, "name":"Surge"},
    {"id":21, "name":"I'm All Ears"},
    {"id":22, "name":"Hex Haunted Ground"},
    {"id":23, "name":"Whispers"},
    {"id":24, "name":"Enduring"},
    {"id":25, "name":"Thanatophobia"},
    {"id":26, "name":"Brutal Strength"},
    {"id":27, "name":"Hex Crowd Control"},
    {"id":28, "name":"Eruption"},
    {"id":29, "name":"Oppression"},
    {"id":30, "name":"Bitter Murmur"},
    {"id":31, "name":"Blood Warden"},
    {"id":32, "name":"Dragon's Grip"},
    {"id":33, "name":"Stridor"},
    {"id":34, "name":"Trail of Torment"},
    {"id":35, "name":"Spirit Fury"},
    {"id":36, "name":"Rancor"},
    {"id":37, "name":"Lightborn"},
    {"id":38, "name":"Remember Me"},
    {"id":39, "name":"Hex Retribution"},
    {"id":40, "name":"Shadowborn"},
    {"id":41, "name":"No Way Out"},
    {"id":42, "name":"Play With Your Food"},
    {"id":43, "name":"Dark Devotion"},
    {"id":44, "name":"Spies From The Shadows"},
    {"id":45, "name":"Forced Penance"},
    {"id":46, "name":"Franklin's Demise"},
    {"id":47, "name":"Distressing"},
    {"id":48, "name":"Hysteria"},
    {"id":49, "name":"Hex Thrill of the Hunt"},
    {"id":50, "name":"Nemesis"},
    {"id":51, "name":"Hex The Third Seal"},
    {"id":52, "name":"Iron Maiden"},
    {"id":53, "name":"Agitation"},
    {"id":54, "name":"Deathbound"},
    {"id":55, "name":"Overcharge"},
    {"id":56, "name":"Hex Huntress Lullaby"},
    {"id":57, "name":"Dying Light"},
    {"id":58, "name":"Fire Up"},
    {"id":59, "name":"Knock Out"},
    {"id":60, "name":"Coup de Grâce"},
    {"id":61, "name":"Dead Man's Switch"},
    {"id":62, "name":"Blood Echo"},
    {"id":63, "name":"Unnerving Presence"},
    {"id":64, "name":"Coulrophobia"},
    {"id":65, "name":"Hex Blood Favour"},
    {"id":66, "name":"Mindbreaker"},
    {"id":67, "name":"Mad Grit"},
    {"id":68, "name":"Hangman's Trick"},
    {"id":69, "name":"Iron Grasp"},
    {"id":70, "name":"Deerstalker"},
    {"id":71, "name":"Hoarder"},
    {"id":72, "name":"Zanshin Tactics"},
    {"id":73, "name":"Bloodhound"},
    {"id":74, "name":"Unrelenting"},
    {"id":75, "name":"Predator"},
    {"id":76, "name":"Cruel Limits"},
    {"id":77, "name":"Gearhead"},
    {"id":78, "name":"Furtive Chase"},
    {"id":79, "name":"Beast Of Prey"},
    {"id":80, "name":"Insidious"},
    {"id":81, "name":"Territorial Imperative"},
    {"id":82, "name":"Overwhelming Presence"},
    {"id":83, "name":"Monstrous Shrine"}
]

killersObject = [
    {"id":0, "name":"Trapper", "free":true},
    {"id":1, "name":"Wraith", "free":true},
    {"id":2, "name":"Hillbilly", "free":true},
    {"id":3, "name":"Nurse", "free":true},
    {"id":4, "name":"Huntress", "free":true},
    {"id":5, "name":"Shape", "free":false},
    {"id":6, "name":"Hag", "free":false},
    {"id":7, "name":"Doctor", "free":false},
    {"id":8, "name":"Cannibal", "free":false},
    {"id":9, "name":"Nightmare", "free":false},
    {"id":10, "name":"Pig", "free":false},
    {"id":11, "name":"Clown", "free":false},
    {"id":12, "name":"Spirit", "free":false},
    {"id":13, "name":"Legion", "free":false},
    {"id":14, "name":"Plague", "free":false},
    {"id":15, "name":"Ghost Face", "free":false},
    {"id":16, "name":"Demogorgon", "free":false},
    {"id":17, "name":"Oni", "free":false},
    {"id":18, "name":"Deathslinger", "free":false},
    {"id":19, "name":"Executioner", "free":false},
    {"id":20, "name":"Blight", "free":false},
    {"id":21, "name":"Twins", "free":false},
    {"id":22, "name":"Trickster", "free":false},
    {"id":23, "name":"Nemesis", "free":false}
]